artefactual-labs/enduro

README.md
codecov.yml
internal/nha/parse_test.go

tests: codecov fixes

---

internal/collection/collection.go
internal/collection/fake/mock_collection.go
internal/workflow/local_activities.go
internal/workflow/policies.go
internal/workflow/processing.go
internal/workflow/processing_test.go
internal/workflow/semaphore.go

workflow: handle parsing errors gracefully

---

internal/nha/activities/prod.go
internal/nha/activities/prod_test.go
internal/workflow/activities/acquire_pipeline.go
internal/workflow/processing.go
internal/workflow/processing_test.go
internal/workflow/receipts.go
internal/workflow/receipts_test.go
internal/workflow/semaphore.go
main.go

This work focuses on cancelation management when it is caused by a session
worker quitting or becoming unavailable. The workflow section that uses the
session attempts to re-run the relevant activities.
Workflow cancelation (root context) has the same results, the workflow returns
and the defer is executed.

workflow: recover from canceled workflows

---

.github/workflows/mod.yml
.github/workflows/test.yml
go.mod
go.sum

Added a CI check so we don't forget to run `go mod tidy`.

Add go.mod check

---

enduro.toml
go.mod
internal/collection/workflow.go
internal/validation/config.go
internal/validation/validate.go
internal/validation/validate_test.go
internal/workflow/activities/activities.go
internal/workflow/activities/validate.go
internal/workflow/processing.go
main.go

Connected to https://github.com/artefactual-labs/enduro/issues/120

workflow: add transfer validation capability

---

internal/pipeline/pipeline.go
internal/pipeline/pipeline_test.go
internal/pipeline/registry.go
internal/pipeline/sync/LICENSE
internal/pipeline/sync/semaphore/semaphore.go
internal/pipeline/sync/semaphore/semaphore_test.go
internal/workflow/semaphore.go

This commit copies the original sync/semaphore to allow us making some
planned customizations.

Fork sync/semaphore

---

internal/workflow/processing.go
internal/workflow/semaphore.go

This commit uses a disconnected context to release the pipeline. It
ensure that we're releasing during cancellation where the regular
context is marked as done.
WaitForCancellation is set to false, this prevents the activities to
fail with `TimeoutType: HEARTBEAT` when Enduro is restarted.
Connects to https://github.com/artefactual-labs/enduro/issues/272.

Use disconnected ctx to release pipeline

---

internal/nha/parse.go
internal/nha/parse_test.go

Capture identifiers not based on RFC 4122

---

internal/workflow/processing.go
internal/workflow/semaphore.go
internal/workflow/semaphore_test.go

Fixes https://github.com/artefactual-labs/enduro/issues/324.

Release pipeline slot before delivering receipts

---

internal/api/api.go

Fixes https://github.com/artefactual-labs/enduro/issues/380.

Avoid writing errors if conn is hijacked

---

internal/api/api.go
internal/api/middleware.go
internal/api/middleware_test.go

This fixes https://github.com/artefactual-labs/enduro/issues/531.

Use writeTimeout middleware to set write deadlines

---

ui/src/App.vue
ui/src/store/pipeline/index.ts
ui/src/views/Pipeline.vue
ui/src/views/PipelineList.vue
ui/vite.config.js

Add pipelines tab

---

internal/workflow/activities/poll_ingest.go
internal/workflow/activities/poll_transfer.go

Log transfer/ingest status polling errors

---

main.go

Return exit code -1 if group errors

---

internal/nha/activities/hari_test.go
internal/nha/activities/prod_test.go
internal/workflow/manager/manager.go
internal/workflow/manager/manager_test.go

HariURL and attributes appear case sensitive. Setting to lower case ensures readability

Fix HariURL format error

---

enduro.toml
internal/pipeline/pipeline.go
internal/workflow/activities/bundle.go
internal/workflow/processing.go
website/content/en/docs/user-manual/configuration.md

Adds a config option to the pipeline settings to enable/disable unbagging bagged transfers

Add config option for unbagging

---

enduro.toml
internal/workflow/async.go
internal/workflow/policies.go
internal/workflow/processing.go
internal/workflow/processing_test.go
internal/workflow/receipts_test.go
internal/workflow/semaphore.go
internal/workflow/semaphore_test.go
main.go

This PR will make configurable the activity heartbeats and throttle intervals in Temporal workflows.

Make heartbeat timeouts and intervals configurable

---

website/content/en/docs/_index.md

Based on a request from BUD. Change summary: 
* Remove mention of "proof of concept" from documentation index
* Bring overall description more in-line with current SDPS version of Enduro

Update index project description

---

website/package-lock.json

Fixes https://github.com/advisories/GHSA-2p57-rm9w-gvfp

Commit results of `npm audit fix`

---

ui/src/views/CollectionShowWorkflow.vue

Workflow History not displaying Fix

---

internal/batch/workflow.go
internal/workflow/activities/bundle.go
internal/workflow/activities/bundle_test.go

Solves https://github.com/artefactual-labs/enduro/issues/571

Ignore hidden files in batch
