artefactual-labs/enduro

- enduro.toml
- internal/filenotify/README.md
- internal/filenotify/filenotify.go
- internal/filenotify/fsnotify.go
- internal/filenotify/poller.go
- internal/filenotify/poller_test.go
- internal/watcher/config.go
- internal/watcher/filesystem.go
In this pull request, filesystemWatcher learns to monitor directories using
polling when the inotify API can't be set up. It can also be enforced via
configuration, in `enduro.toml`:
```toml
[[watcher.filesystem]]
inotify = false # default is true
```
The new `filenotify` package is a copy from the one found in the Moby project,
since they haven't published it as a module. This package provides an interface
with an API similar to the fsnotify struct so the changes required were pretty
small. Credits to Brian Goff and the Moby team.
> watcher: support filesystem polling

- enduro.toml
- go.mod
- go.sum
- hack/test-dpj/Makefile
- internal/pipeline/pipeline.go
- internal/pipeline/pipeline_test.go
- internal/workflow/activities/acquire_pipeline.go
- internal/workflow/activities/activities.go
- internal/workflow/local_activities.go
- internal/workflow/policies.go
- internal/workflow/processing.go
- main.go
This is the simplest version I could think of to address resource constraint in response to @jorikvankemenade's feature request. It uses a local weighted semaphore with capacity determined via configuration. It does not require changes in Archivematica (which won't have native rate-limiting until v1.12 at the very least), but it can't tell if a pipeline was already busy from interacting with other users (other than Enduro).
It is definitely improvable. Major limitations:
* The semaphore is local to the main process. We'd need to move to a distributed semaphore once we start deploying Enduro in a distributed fashion.
* All collections go into "in progress" even when they're queued or blocked waiting for the semaphore to be acquired. We could add an intermediate status, e.g. "queued"?
* If …
> pipeline: add local weighted semaphores

- internal/workflow/activities/acquire_pipeline.go
- internal/workflow/local_activities.go
- internal/workflow/policies.go
- internal/workflow/processing.go
* Retry acquire so the activity doesn't block forever.
* Recover when release operation panics.
> pipeline: polish semaphore usage

- internal/nha/activities/activities.go
- internal/workflow/processing.go
- internal/workflow/processing_test.go
* Send receipts only when processing succeeded.
* Send "prod" only when "hari" succeeds.
* First workflow tests!
> workflow: deliver receipts sequentially 

- internal/pipeline/status.go
- internal/workflow/policies.go
When transferring multiple large files we get ingest timeouts as described in #51 and download timeouts as discussed in #50. This PR addresses both issues:
1. `IngestStatus` retries on on `net.Error` timeouts. 
1.  `withActivityOptsForLongLivedRequest` defines a longer timeout, allowing large downloads to finish.
1. `withActivityOptsForLongLivedRequest` does not retry on the activity timing out. Thus making sure that a *complete* download will only time out once. 
I think that we could maybe improve a little bit on the error handling in `IngestStatus`, see my comments in commit d1dc144. However, this might be more appropriately scoped with some possible future error handling work. 
Closes #50, #51
> timeouts: improve timeout handling for large files 

- enduro.toml
- internal/filenotify/filenotify.go
- internal/filenotify/poller.go
- internal/watcher/config.go
- internal/watcher/filesystem.go
- main.go
This pull request introduces two changes that help us work with watched directories when the transfers are ~too~ big (see #41 for more details).
* We've updated filenotify so the poller (filesystem watcher when inotify is unavailable) subscribes to rename events. The inotify implementation was already doing that so no changes were required.
* Additionally, we've added a new configuration attribute `[[watcher.filesystem]] ignore` (only relevant to fs watchers) to ignore events where the names don't match the defined regular expression. It uses the stdlib [regex](https://golang.org/pkg/regexp/) package and it matches strings using the [`MatchString`](https://godoc.org/regexp#MatchString) method.
For example, the watcher below will ignore files with extension ".mft". E.g. file "package.mft" …
> Make fs watchers usable for big transfers

- .github/workflows/release.yml
We where using nha/ , but it's time to split enduro rpm's into it's own
repository.
> Update rpm repository where the package is built

- internal/nha/activities/hari.go
- internal/nha/activities/hari_test.go
v0.28.1 introduced the ability to trim down the AVLXML document (https://github.com/artefactual-labs/enduro/commit/a23c5e4e7b28720a600f64721fd0cf623abca18b). What's missing in that change and this PR fixes is to restrict that behaviour to AVL SIPs only.
The tests show how the document is untouched with other types, while slimDown produces a XML document where `pasientjournal` is not included even when provided by the user.
> nha: trim down avlxml only in avl sips

- .github/workflows/lint.yml
- .github/workflows/mod.yml
- .github/workflows/test.yml
- hack/coverpkgs.sh
Measuring test coverage accurately requires ignoring certain packages that are
not under our control, e.g. generated code, tooling, etc... This commit uses
`go test -coverpkg` to ensure that coverage analysis is applied to packages
only matching the pattern given.
> Fix coverage report

- internal/api/api.go
- internal/collection/download.go
This is a potential fix for an error we've seen where file streaming stops abruptly. I believe we're exceeded the write timeout. Unfortunately, we can only set it for the whole server.
Connects to https://github.com/artefactual-labs/enduro/issues/255.
> Unset WriteTimeout to allow streaming

- enduro.toml
- go.mod
- go.sum
- internal/pipeline/pipeline.go
- internal/pipeline/status.go
- internal/pipeline/status_test.go
- internal/workflow/activities/poll.go
- internal/workflow/activities/poll_ingest.go
- internal/workflow/activities/poll_ingest_test.go
- internal/workflow/activities/poll_test.go
- internal/workflow/activities/poll_transfer.go
- internal/workflow/activities/poll_transfer_test.go
This commit updates the retry strategy when polling the Status API:
* 4xx client errors are now considered non-retryable, and
* 5xx server errors will be retried with a delayy of five seconds, and a
deadline of five minutes, and
* 400 status code, which the Archivematica API chooses to send when
raising a type o known server error (i.e. no jobs), will be retried as
we do with 5xx errors.
Fixes https://github.com/artefactual-labs/enduro/issues/282.
> Update retry strategy when polling Status API

- internal/pipeline/pipeline_test.go
- internal/pipeline/sync/semaphore/semaphore.go
- internal/pipeline/sync/semaphore/semaphore_test.go
This commit ensures that the weight of the semaphore is never below zero
which was happening when releasing more than was held. This was seen
when workflows were resumed after the process was killed and we release
when the hold had been lost.
Connects to https://github.com/artefactual-labs/enduro/issues/272.
> Force semaphore weight to be unsigned

- internal/nha/activities/prod_test.go
- Use OID as parent field for dpj/epj
- Use OID as avlxml identifier
> Update tests for NHA receipts

- ui/src/views/CollectionShow.vue
This also ensures that the identifier is shown even if the workflow failed.
Fixes https://github.com/artefactual-labs/enduro/issues/394.
> Show AIPID as soon as it's available

- internal/nha/activities/hari.go
- internal/nha/activities/hari_test.go
Later versions of avlxml include an optional tag 'generertdato':
```
<xs:complexType name="avlevering">
<xs:annotation>
<xs:documentation>Avleveringslisten i AVLXML</xs:documentation>
</xs:annotation>
<xs:sequence>
<xs:element name="avlxmlversjon" type="avlmdk:avlxmlversjon"/>
<xs:element name="avleveringsidentifikator" type="avlmdk:avleveringsidentifikator"/>
<xs:element name="avleveringsbeskrivelse" type="avlmdk:avleveringsbeskrivelse"/>
<xs:element minOccurs="0" name="generertdato" type="avlmdk:arkDATO"/>
<xs:element name="arkivskaper" type="avlmdk:arkivskaper"/>
<xs:element name="avtale" type="avtale"/>
<xs:element maxOccurs="unbounded" name="pasientjournal" type="pasientjournal"/>
</xs:sequence>
</xs:complexType>
```
If it exists in the AVLXML inside an ingested avl-sip, it should be …
> NHA: Update to avlxml version 3

- go.mod
- go.sum
- main.go
go.artefactual.dev/tools/log provides the same logger that we use in other Artefactual projects. Easier to setup compared to having to deal with the underling sink, configure zap, etc...
> Use go.artefactual.dev/tools/log

- .gitmodules
- hack/make/dep_hugo.mk
- netlify.toml
- website/config.toml
- website/content/en/docs/development/deps.md
- website/content/en/docs/installation/_index.md
- website/go.mod
- website/go.sum
- website/layouts/swagger/list.html
- website/package.json
hugo now uses its own modules system so we don't need to import docsy using
git submodules.
> Update hugo from 0.113.0 to 0.115.3

- internal/nha/activities/hari_test.go
- internal/nha/activities/prod_test.go
- internal/workflow/activities/bundle.go
- internal/workflow/activities/bundle_test.go
- internal/workflow/activities/cleanup.go
- internal/workflow/activities/delete_original.go
- internal/workflow/activities/dispose_original.go
- internal/workflow/activities/download.go
- internal/workflow/manager/manager.go
- internal/workflow/processing_test.go
- main.go
This PR begins the redundancy of manager
> Remove watcher from manager

- Makefile
make list-tested-packages 
```
github.com/artefactual-labs/enduro
github.com/artefactual-labs/enduro/internal/api
github.com/artefactual-labs/enduro/internal/bagit
github.com/artefactual-labs/enduro/internal/batch
github.com/artefactual-labs/enduro/internal/bundler
github.com/artefactual-labs/enduro/internal/collection
github.com/artefactual-labs/enduro/internal/db
github.com/artefactual-labs/enduro/internal/filenotify
github.com/artefactual-labs/enduro/internal/fsutil
github.com/artefactual-labs/enduro/internal/metadata
github.com/artefactual-labs/enduro/internal/nha
github.com/artefactual-labs/enduro/internal/nha/activities
github.com/artefactual-labs/enduro/internal/pipeline
github.com/artefactual-labs/enduro/internal/pipeline/sync/semaphore …
```
> Clean up IGNORED_PACKAGES

- .github/workflows/lint.yml
- .github/workflows/mod.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Fixes a Github actions error:
```
Node.js 16 actions are deprecated. Please update the following actions
to use Node.js 20: actions/setup-go@v4.
```
> Bump Github actions/setup-go from v4 to v5

- internal/workflow/processing.go
- main.go
Fix a couple of gosec warnings:
- G404: Insecure random number source (rand)
- G114: Use of net/http serve function that has no support for setting timeouts
I meant to go further and address the many "G304: Potential file inclusion via variable" gosec issues, but I'm not clear how to ensure path safety without potentially breaking current deployments.
> Fix gosec issues

- README.md
- ui/src/App.vue
- website/content/en/docs/contribution-guidelines/docs.md
The https://enduroproject.netlify.com URL is no longer resolving for some reason.
> Update netlify.com -> netlify.app

- Makefile
- hack/make/dep_hugo.mk
- netlify.toml
- website/.go-version
- website/content/en/docs/api/_index.md
- website/content/en/docs/contribution-guidelines/docs.md
- website/content/en/docs/development/environment.md
- website/content/en/docs/installation/_index.md
- website/go.mod
- website/go.sum
- website/hugo.toml
- website/package-lock.json
- website/package.json
- Update hugo
- Add angle brackets to http://localhost URLs to make them links.
>  Link localhost URLs

- ui/src/store/collection/index.ts
Previously, the `collectionList` generated code was not transforming the objects to the desired form. It does now, so we no longer need to do it manually. In other words the objects are already in the expected shape, from the generated API code.
fixes #611
> Fix missing Started and Stored collection data

- internal/workflow/activities/cleanup.go
- internal/workflow/processing.go
This PR will fix an issue where the files created in the `processingDir` (when configured in the pipeline) were never cleaned up by Enduro.
It also changes the (Temporal) context that the `clean-up` activity uses to a disconnected one, this avoids the (unintended) cancellation of the context when the session gets released.
> Clean up files in processingDir (temporary staging dir)

- ui/src/filters/index.ts
- ui/src/views/CollectionShowWorkflow.vue
This MR fix the formatting for dates in the workflow Tab. At some point the Temporal payload for the event history changed and now we need to account for that.
This is how is looks right now: 
This is after the fix: 
Fixes #628
> Fix dates in Workflow tab

- internal/api/api.go
- internal/api/debug_middleware.go
This MR tries to address a problem when using Enduro with the API in Debug mode.
The Debug middle-ware prints to stdout details about the request, including the bodies of both the request and response. This is usually what we want, except when we are downloading binary files (like compressed AIPs), when the Download package endpoint is hit with download request, the Download fails (if debug = true) while the payload is printed (a binary blob) to stdout. In this usecase the download fails (bytes get dropped consistently).
To solve this issue I decided to avoid printing the response body when the `Content-Type` is of: `application/x-7z-compressed`. Since the Debug middleware belongs to the Goa library I could not modify it, I decided to copy the exact middleware and modify only what I …
> Replace API Debug Middleware
